102300334 - work1
west2-online-reserve/collection-java pull request #40
Opened 2023-09-24 16:05 UTC by MasterLin34

按照个人理解实现了西瓜摊的所有功能，由于对编程语言0基础，九月初才开始学习Java，整体作业完成仍十分粗糙，希望组长指正

2023-09-25 03:26 UTC, emptyOVO reviewed
交互可以不用那么复杂，Scannner测试里不用new那么多个出来，在西瓜摊位里面定义的方法里面也不用new，然后建议测试单独写一个测试类

2023-09-25 12:23 UTC, Poldroc commented
参考别人的作业格式，注意包结构，还有截图

2023-09-26 12:02 UTC, Poldroc approved these changes
最好一个类一个文件，类名与文件名相同

2023-09-26 12:02 UTC, Poldroc commented on work1/MasterLin34/Watermalon.java
> +	}
stocking作为参数传进来了，为什么要再输入？

2023-09-26 12:02 UTC, Poldroc commented on work1/MasterLin34/Watermalon.java
> +	}
进货负数的情况也考虑一下

2023-09-26 12:02 UTC, Poldroc commented on work1/MasterLin34/Watermalon.java
> +}
看好作业要求，需要传入的是数组

2023-09-26 12:02 UTC, Poldroc commented on work1/MasterLin34/Watermalon.java
> +	}
同上，不需要过多的scanner

2023-09-26 12:03 UTC, Poldroc reviewed
一个类一个文件，类名与文件名相同

2023-09-27 17:31 UTC, Poldroc requested changes

2023-09-27 17:31 UTC, Poldroc commented on work1/MasterLin34/Watermalon.java
> +class Stand{
？

2023-09-27 17:31 UTC, Poldroc commented on collection-java
换成idea了吗

2023-09-27 23:43 UTC, MasterLin34 commented on collection-java
已经换成idea了 格式还是不对吗

2023-09-28 11:31 UTC, merged